services:
  web:
    image: ${REPO}-${WEBSERVER}
    container_name: ${STACK_NAME}_web
    restart: always
    ports:
      - "${HOST_IP}:${WEB_PORT}:${WEB_PORT}"
      - "${HOST_IP}:${WEBS_PORT}:${WEBS_PORT}"
    volumes:
      - ${STACK_SRC}:/var/www/html
      - ./config/moodle/config.mysql.php:/var/www/html/config.php
      - ${STACK_VOLUME_WEB}/moodle/data:/var/www/moodledata
      - ${STACK_VOLUME_WEB}/phpunit/moodle/data:/var/www/phpu_moodledata
      - ${STACK_VOLUME_WEB}/moodle/certbot/www/:/var/www/certbot/:rw
      - ${STACK_VOLUME_WEB}/moodle/certbot/conf/:/etc/letsencrypt/:rw
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PREFIX=${MYSQL_PREFIX}
      - MYSQL_PORT=${MYSQL_PORT}
      - FORCE_DEBUG=${FORCE_DEBUG}
      - ENABLE_CRON=${ENABLE_CRON}
      - WEBSERVER=${WEBSERVER}
      - WEB_PORT=${WEB_PORT}
      - WEBS_PORT=${WEBS_PORT}
      - DOMAIN=${DOMAIN}
      - CERT_COUNTRY=${CERT_COUNTRY}
      - CERT_STATE=${CERT_STATE}
      - CERT_CITY=${CERT_CITY}
      - CERT_ORG=${CERT_ORG}
      - CERT_ORG_UNIT=${CERT_ORG_UNIT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - SERVERURL=${SERVERURL}
      - WWWROOT=${WWWROOT}
      - TZ=${TZ}
      - PHPUNIT_ENABLED=${PHPUNIT_ENABLED}
      - PHPU_MYSQL_PREFIX=${PHPU_MYSQL_PREFIX}
      - PHPU_MYSQL_DATABASE=${PHPU_MYSQL_DATABASE}
      - PHPU_MYSQL_USER=${PHPU_MYSQL_USER}
      - PHPU_MYSQL_PASSWORD=${PHPU_MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - moodle_network
      - certbot_network
      - db_network
      - db_phpunit_network
      - db_slave_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
  certbot:
    image: certbot/certbot:latest
    container_name: ${STACK_NAME}_certbot
    restart: always
    networks:
      - certbot_network
    depends_on:
      - web
    volumes:
      - ${STACK_VOLUME_WEB}/moodle/certbot/www/:/var/www/certbot/:rw
      - ${STACK_VOLUME_WEB}/moodle/certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
  db:
    # image: mysql:8.0
    build:
      context: ./docker-files/db/mysql
    container_name: ${STACK_NAME}_db
    restart: always
    # ports:
    #   - "${MYSQL_DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${STACK_VOLUME_DB}/master/${DBTYPE}/data:/var/lib/mysql
      - ./config/db/master/mysql/my.cnf:/etc/my.cnf
      # - ./backup/mysql:/var/mysql/backup/
      - ./config/db/master/mysql/init.sql.template:/init.sql.template
      - ./config/db/master/mysql/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    entrypoint: ["/custom-docker-entrypoint.sh"]
    networks:
      - db_network
      - pma_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${STACK_NAME}_phpmyadmin
    restart: always
    ports:
      - "${HOST_IP}:${MYSQL_PMA_PORT}:80"
      - "${HOST_IP}:${MYSQL_PMAS_PORT}:443"
    environment:
      - PMA_ARBITRARY=1
      # - PMA_HOST=db

      # Careful: Uncomment these will expose your phpmyadmin login.
      # - PMA_USER=${MYSQL_USER}
      # - PMA_PASSWORD=${MYSQL_PASSWORD}
      # - PMA_DATABASE=${MYSQL_DATABASE}
      # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: >
      sh -c "sed 's|/etc/ssl/certs/ssl-cert-snakeoil.pem|/etc/letsencrypt/live/${DOMAIN}/fullchain.pem|g' /etc/apache2/sites-available/default-ssl.conf > /tmp/default-ssl.conf &&
            sed -i 's|/etc/ssl/private/ssl-cert-snakeoil.key|/etc/letsencrypt/live/${DOMAIN}/privkey.pem|g' /tmp/default-ssl.conf &&
            mv /tmp/default-ssl.conf /etc/apache2/sites-available/default-ssl.conf &&
            if [ ! -f /etc/phpmyadmin/config.secret.inc.php ]; then
              echo \"<?php\\n\\\$$cfg['blowfish_secret'] = '$(php -r 'echo bin2hex(random_bytes(32));')';\" > /etc/phpmyadmin/config.secret.inc.php;
            fi && 
            apache2ctl -D FOREGROUND &
            while true; do
                sleep 12h
                apache2ctl graceful
            done
        "
    depends_on:
      - db
    networks:
      - pma_network
    volumes:
      - ${STACK_VOLUME_WEB}/moodle/certbot/conf/:/etc/letsencrypt/:ro
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}
networks:
  moodle_network:
  certbot_network:
  pma_network:
    external: true
    name: ${STACK_NAME}_pma_network
  db_network:
  db_phpunit_network:
    external: true
    name: ${STACK_NAME}_db_phpunit_network
  db_slave_network:
    external: true
    name: ${STACK_NAME}_db_slave_network