services:
  db_slave:
    runtime: runc
    # image: mariadb:10.6
    build:
      context: ./docker-files/db/mariadb
    container_name: ${STACK_NAME}_db_slave
    restart: always
    # ports:
    #   - "${MARIADB_DB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - TZ=${TZ}
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
      - MASTER_DB_HOST=db
    volumes:
      - ${STACK_VOLUME_DB}/slave/${DBTYPE}/data:/var/lib/mysql
      - ./config/db/slave/mariadb/my.cnf:/etc/mysql/conf.d/my.local.cnf
      - ./config/db/slave/mariadb/init.sql.template:/init.sql.template
      - ./config/db/slave/mariadb/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    entrypoint: ["/custom-docker-entrypoint.sh"]
    networks:
      - pma_network
      - db_slave_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

networks:
  pma_network:
    external: true
    name: ${STACK_NAME}_pma_network
  db_slave_network:
    external: true
    name: ${STACK_NAME}_db_slave_network
