services:
  db_phpunit:
    runtime: runc
    # image: mariadb:10.6
    build:
      context: ./docker-files/db/mariadb
    container_name: ${STACK_NAME}_phpunit_db
    restart: always
    # ports:
    #   - "${PHPU_MARIADB_DB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${PHPU_MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${PHPU_MARIADB_DATABASE}
      - MARIADB_USER=${PHPU_MARIADB_USER}
      - MARIADB_PASSWORD=${PHPU_MARIADB_PASSWORD}
      - TZ=${TZ}
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${STACK_VOLUME_DB}/phpunit/${DBTYPE}/data:/var/lib/mysql
      - ./config/db/phpunit/mariadb/my.cnf:/etc/mysql/conf.d/my.local.cnf
      - ./config/db/phpunit/mariadb/init.sql.template:/init.sql.template
      - ./config/db/phpunit/mariadb/custom-docker-entrypoint.sh:/custom-docker-entrypoint.sh
    entrypoint: ["/custom-docker-entrypoint.sh"]
    networks:
      - db_phpunit_network
      - pma_network
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY}

networks:
  pma_network:
    external: true
    name: ${STACK_NAME}_pma_network
  db_phpunit_network:
    external: true
    name: ${STACK_NAME}_db_phpunit_network
